### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Shrewd** [klo2k/nexus3-docker#30]
Hi!
I'm trying to push some docker images, and trying to configure the https connector but I get this error: "Unsupported HTTP Scheme: https"

```
024-07-04 01:27:40,027+0000 INFO  [qtp481973177-675] admin org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Updating repository: docker -> OrientConfiguration{repositoryName='docker', recipeName='docker-hosted', attributes={docker={forceBasicAuth=true, v1Enabled=false}, storage={blobStoreName=default, strictContentTypeValidation=true, writePolicy=ALLOW, latestPolicy=false}, component={proprietaryComponents=false}}}
2024-07-04 01:27:53,830+0000 INFO  [qtp481973177-674] admin org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl - Updating repository: docker -> OrientConfiguration{repositoryName='docker', recipeName='docker-hosted', attributes={docker={httpsPort=8085.0, forceBasicAuth=true, v1Enabled=false}, storage={blobStoreName=default, strictContentTypeValidation=true, writePolicy=ALLOW, latestPolicy=false}, component={proprietaryComponents=false}}}
2024-07-04 01:27:53,839+0000 WARN  [qtp481973177-674] admin org.sonatype.nexus.repository.docker.internal.DockerConnectorFacetImpl - Could not configure https connector on port 8085 for docker repository docker
org.sonatype.nexus.bootstrap.jetty.UnsupportedHttpSchemeException: Unsupported HTTP Scheme: https
	at org.sonatype.nexus.internal.jetty.ConnectorRegistrarImpl.validate(ConnectorRegistrarImpl.java:128)
	at org.sonatype.nexus.internal.jetty.ConnectorRegistrarImpl.addConnector(ConnectorRegistrarImpl.java:84)
	at org.sonatype.nexus.repository.docker.internal.DockerConnectorFacetImpl.startConnector(DockerConnectorFacetImpl.java:154)
	at org.sonatype.nexus.repository.docker.internal.DockerConnectorFacetImpl.doStart(DockerConnectorFacetImpl.java:131)

```
Any help to set it?

**Comment by klo2k** [comment]
I left mine as HTTP, but I put NGINX in front for https.

I've never tried doing native https myself - perhaps this page can help?
https://help.sonatype.com/en/ssl-and-repository-connector-configuration.html
